---
# tasks file for tower_validate_org
- name: Retrieve a list of organizations
  uri:
    method: GET
    headers:
      Authorization: "{{ auth }}"
    status_code: 200
    url: "{{ target }}/api/v2/organizations/?name={{ org_name | urlencode }}"
    return_content: yes
  register: res

- name: Get the ID for the Org
  no_log: true
  set_fact:
    organization: "{{ org }}"
  when: "org_name == org.name"
  loop: "{{ res.json.results }}"
  loop_control:
    loop_var: org

- name: Check if the org was found
  fail:
    msg: The organization '{{ org_name }}' was not found! Unable to continue
  when: 'organization is undefined'

- name: Presenting match
  debug: var=organization
